parking_system/parking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parking.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parking_system/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signout/', views.LogoutView.as_view(next_page='users:signin'), name='signout'),
    path('profile/', views.UserUpdateView.as_view(), name='profile'),
    path('reset-password/', 
         views.ResetPasswordView.as_view(), 
         name='password_reset'),
    path('reset-password/done/', 
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

parking_system/users/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tg_token = models.CharField(max_length=30, null=False)
    balance = models.fields.FloatField(default=0)

    def __str__(self):
        return self.user.username

parking_system/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

parking_system/users/views.py
from typing import Any
from django.http.response import HttpResponse as HttpResponse
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin


from .forms import SignupForm
from django.contrib.auth.models import User


class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:signin')


class SigninView(LoginView):
    template_name = 'users/signin.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('parking:cars')
    

@method_decorator(login_required, name='dispatch')
class UserUpdateView(UpdateView):
    model = User
    template_name = 'users/profile.html'
    fields = ['first_name', 'last_name', 'email']
    success_url = reverse_lazy('users:profile')


    def get(self, request, **kwargs):
        self.object = User.objects.get(username=self.request.user)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context = self.get_context_data(object=self.object, form=form)
        return self.render_to_response(context)
    
    
    def get_object(self, queryset=None):
        return self.request.user
    

class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

parking_system/users/templates/users/password_reset.html
{% extends "parking/base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        <div class="mb-3">
            <h2 class="display-6 fw-normal text-body-emphasis">Password reset</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            <p>
                <label for="id_email">Email:</label>
                <input type="email" class="form-control" name="email" autocomplete="email" maxlength="50" required="" id="id_email">
            </p>
                <button type="submit" class="btn btn-primary">Request password reset</button>
        </form>
    </div>
</div>
{% endblock %}

parking_system/users/templates/users/password_reset_complete.html
{% extends "parking/base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5 text-center">
        <div class="mb-3">
            <h2 class="display-6 fw-normal text-body-emphasis">Password reset complete!</h2>
        </div>
    </div>
</div>

{% endblock %}

parking_system/users/templates/users/password_reset_confirm.html
{% extends "parking/base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-5">
        <div class="mb-3">
            <h2 class="display-6 fw-normal text-body-emphasis">Enter new password</h2>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors}}
            <label class="form-label" for="id_new_password1">New password:</label>
            <input type="password" class="form-control" name="new_password1" autocomplete="new-password" required="" aria-describedby="id_new_password1_helptext" id="id_new_password1">
            <span class="text-danger">{{ form.errors.new_password1 }}</span>
            <span class="helptext" id="id_new_password1_helptext"></span></p><ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul>
            <label class="form-label" for="id_new_password2">New password confirmation:</label>
            <input type="password" class="form-control mb-3" name="new_password2" autocomplete="new-password" required="" id="id_new_password2">
            <span class="text-danger">{{ form.errors.new_password2 }}</span>
            <button type="submit" class="btn btn-primary" >Save new password</button>
        </form>
    </div>
</div>

{% endblock %}

parking_system/users/templates/users/password_reset_done.html
{% extends "parking/base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="col-8 text-center">
        <div class="mb-3">
            <h2 class="display-6 fw-normal text-body-emphasis">Password reset request sent</h2>
        </div>
        <div class="blockquote">
            <p>We've emailed you with instructions on how to reset your password.</p>
        </div>
    </div>
</div>

{% endblock %}

parking_system/users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

parking_system/users/templates/users/profile.html
{% extends "parking/base.html" %}

{% block content %}
<div class="row">
    <div class="d-flex justify-content-center">
    <div class="col-5">
        <div class="mb-3">
            <h2 class="display-6 fw-normal text-body-emphasis">Profile</h2>
        </div>
        <form method="POST" action="{% url 'users:profile' %}">
            {% csrf_token %}
            <label class="form-label">Username</label>
            <input type="text" id="inputUsername" name="username" class="form-control mb-3" disabled value="{{ user.username }}"/>
            <label for="inputFirstname" class="form-label">First name</label>
            <input type="text" id="inputFirstname" name="first_name" class="form-control mb-3" value="{{ user.first_name }}"/>
            <span class="text-danger">{{ form.errors.first_name }}</span>
            <label for="inputLastname" class="form-label">Last name</label>
            <input type="text" id="inputLastname" name="last_name" class="form-control mb-3" value="{{ user.last_name }}"/>
            <span class="text-danger">{{ form.errors.last_name }}</span>
            <label for="InputEmail" class="form-label">Email address</label>
            <input type="email" class="form-control mb-3" id="InputEmail" name="email" placeholder="name@example.com" value="{{ user.email }}"/>
            <span class="text-danger">{{ form.errors.email }}</span>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
</div>
{% endblock %}

parking_system/users/templates/users/signin.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Smart Parking Manager</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'users/signin.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </head>
    <body class="d-flex align-items-center py-4">
        <main class="form-signin w-100 m-auto">
            <div class="container text-center">
                <img class="mb-4" src="{% static 'parking/logo.jpg' %}" alt="" width="72" height="57">
                <h1 class="h3 mb-5 fw-normal">Smart Parking Manager</h1>
                {% if form.non_field_errors %}
                <div>
                    <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>
                </div>
                {% endif %}
                <form method="POST" action="{% url 'users:signin' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="username" class="form-control" id="username" aria-describedby="emailHelp" name="username">
                    </div>
                    <div class="mb-3">
                    <label for="Password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="Password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary mb-3">Submit</button>
                    <div class="mb-3">
                        <p>Have no account? <a href="{% url 'users:signup' %}">Sign-up</a></p>
                    </div>
                    <div class="text-center">
                        <a href="{% url "users:password_reset" %}" class="text-center"><i>Forgot Password?</i></a>
                    </div>
                </form>
            </div>
        </main>
    </body>
</html>

parking_system/users/templates/users/signup.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Smart Parking Manager</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    </head>
    <body class="d-flex align-items-center py-4">
        <main class="container">
            <div class="row">
                <div class="d-flex justify-content-center">
                <div class="col-5">
                    <div class="mb-3">
                        <h2 class="display-6 fw-normal text-body-emphasis">User sign-up form</h2>
                    </div>
                    <form method="POST" action="{% url 'users:signup' %}">
                        {% csrf_token %}
                        <label class="form-label">Username</label>
                        <input type="text" id="inputUsername" name="username" class="form-control mb-3"/>
                        <span class="text-danger">{{ form.errors.username }}</span>
                        <label for="inputFirstname" class="form-label">First name</label>
                        <input type="text" id="inputFirstname" name="first_name" class="form-control mb-3"/>
                        <span class="text-danger">{{ form.errors.first_name }}</span>
                        <label for="inputLastname" class="form-label">Last name</label>
                        <input type="text" id="inputLastname" name="last_name" class="form-control mb-3"/>
                        <span class="text-danger">{{ form.errors.last_name }}</span>
                        <label for="InputEmail" class="form-label">Email address</label>
                        <input type="email" class="form-control mb-3" id="InputEmail" name="email" placeholder="name@example.com"/>
                        <span class="text-danger">{{ form.errors.email }}</span>
                        <label for="inputPassword1" class="form-label">Password</label>
                        <input type="password" id="inputPassword1" name="password1" class="form-control mb-3"/>
                        <span class="text-danger">{{ form.errors.password1 }}</span>
                        <label for="inputPassword2" class="form-label">Password</label>
                        <input type="password" id="inputPassword2" name="password2" class="form-control mb-3"/>
                        <span class="text-danger">{{ form.errors.password2 }}</span>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
            </div>
        </main>
    </body>
</html>