parking_system/parking/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from . import views

app_name = 'parking'

urlpatterns = [
    path('', views.CarsView.as_view(), name='cars'),
    path('car/', views.CarCreateView.as_view(), name='car_add'),
    path('history/', views.HistoryView.as_view(), name='history'),
    path('parking/', views.parking, name='parking'),
    path('parking_info/', views.SettingsView.as_view(), name='parking_info'),
    path('parking/<pk>/', views.ParkingGreetView.as_view(), name='parking_greet'),
    path('parking_report/', views.parking_report, name='parking_report'),
    path('download_reports/', views.download_reports, name='download_reports'),
    path('delete/<int:id>/', views.delete_car, name='delete_car'),
    path('edit/<int:id>/', views.edit_car, name='edit_car'),
    path('ban/<int:car_id>/', views.ban_car, name='ban_car'),
    path('unban/<int:car_id>/', views.unban_car, name='unban_car'),
    path('search/', views.CarsView.as_view(), name='search_cars'),
    path('searchbanlist/', views.CarsBanList.as_view(), name='search_banned_cars'),
    path('ban_list/', views.CarsBanList.as_view(), name='ban_list'),
    path('debtor_report/', views.DebtorListView.as_view(), name='debtor_report'),
    path('payment/', views.PaymentListView.as_view(), name="payment"),
    path('payment/pay/<int:amount>/', views.PayView.as_view(), name='pay'),
    path('payment/pay_callback/', views.PayCallbackView.as_view(), name='pay_callback'),
    #path('debtor_report/download', views.DebtorListView.as_view(), name='download_debtors'),
]

parking_system/parking_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parking.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

parking_system/users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/', views.SigninView.as_view(), name='signin'),
    path('signout/', views.LogoutView.as_view(next_page='users:signin'), name='signout'),
    path('profile/', views.UserUpdateView.as_view(), name='profile'),
    path('reset-password/', 
         views.ResetPasswordView.as_view(), 
         name='password_reset'),
    path('reset-password/done/', 
         PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

parking_system/parking/models.py
from collections.abc import Iterable
from django.db import models
from django.contrib.auth.models import User


class Car(models.Model):
    reg_mark = models.CharField(max_length=8, null=False, unique=True)
    model = models.CharField(max_length=30, null=False)
    color = models.CharField(max_length=30, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    fare = models.FloatField(default=0)
    confirmed = models.BooleanField(default=False)
    is_banned = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.reg_mark}"

    def total_parking_duration(self):
        total_duration = 0
        parks = self.park_set.all()
        for park in parks:
            if park.out_time:
                duration = (park.out_time - park.in_time).total_seconds()
                total_duration += duration
        return total_duration

    def total_parking_cost(self):
        total_cost = 0
        parks = self.park_set.all()
        for park in parks:
            total_cost += park.cost
        return total_cost


class Park(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    in_time = models.DateTimeField(auto_now_add=True)
    out_time = models.DateTimeField(null=True, blank=True)
    cost = models.FloatField(default=0)

    def duration_to_str(self):
        total_duration_str = ''
        if self.out_time:
            total_duration = (self.out_time - self.in_time).total_seconds()
            hours, remainder = divmod(total_duration, 3600)
            minutes, seconds = divmod(remainder, 60)
            total_duration_str = '{:02}:{:02}:{:02}'.format(int(hours), int(minutes), int(seconds))
        return total_duration_str

    def calculate_cost(self):
        if self.out_time:
            duration_hours = (self.out_time - self.in_time).total_seconds() / 3600
            # Per hour tarification
            if int(duration_hours) != duration_hours:
                duration_hours = int(duration_hours) + 1
            self.cost = duration_hours * self.car.fare


    # Cost calculation when saving the model
    def save(self, *args, **kwargs):
        self.calculate_cost()
        return super().save(*args, **kwargs)


class Ban(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(null=True, blank=True)


class Payment(models.Model):
    amount = models.FloatField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)


class ParkingInfo(models.Model):
    address = models.CharField(max_length=40, null=True)
    places = models.IntegerField(default=0)
    limit = models.FloatField(default=0)
    default_fare = models.FloatField(default=0)

parking_system/parking/forms.py
from django import forms
from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['reg_mark', 'model', 'color', 'fare', 'confirmed']

parking_system/parking/views.py
import csv
from django.conf import settings
from liqpay import LiqPay
from typing import Any
from random import randint

from django.db.models import Q
from django.db.models.base import Model as Model
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import HttpResponse, Http404
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from datetime import datetime, timezone

from users.models import Profile
from .decorators import superuser_required
from .forms import CarForm
from .models import Car, Park, ParkingInfo, Ban, Payment

from numberplate_ukr.main import CarPlateReader


@method_decorator(login_required, name='dispatch')
class CarsView(TemplateView):
    template_name = 'parking/index.html'

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)

        query = self.request.GET.get('q')

        if query:
            if self.request.user.is_superuser:
                cars = Car.objects.filter(
                    (Q(reg_mark__startswith=query) |
                    Q(color__startswith=query) |
                    Q(model__startswith=query)) &
                    Q(is_banned=False)
                ).order_by('confirmed')
            else:
                cars = Car.objects.filter(
                    Q(user=self.request.user) &
                    (Q(reg_mark__startswith=query) |
                     Q(color__startswith=query) |
                     Q(model__startswith=query)) & Q(is_banned=False)
                ).order_by('confirmed')
        else:
            if self.request.user.is_superuser:
                cars = Car.objects.filter(is_banned=False).order_by('confirmed')
            else:
                cars = Car.objects.filter(user=self.request.user)

        context['cars'] = cars
        return context


@method_decorator(login_required, name='dispatch')
class CarCreateView(CreateView):
    model = Car
    fields = ['reg_mark', 'model', 'color', 'fare', 'user', 'confirmed']
    success_url = reverse_lazy("parking:cars")

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['parking_info'] = ParkingInfo.objects.first()
        return context


@method_decorator(login_required, name='dispatch')
class CarsBanList(ListView):
    model = Car
    template_name = 'parking/ban_list.html'
    context_object_name = 'banned_cars'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            if self.request.user.is_superuser:
                cars = Car.objects.filter(
                    (Q(reg_mark__startswith=query) |
                    Q(color__startswith=query) |
                    Q(model__startswith=query)) &
                    Q(is_banned=True)
                ).order_by('confirmed')
            else:
                cars = Car.objects.filter(
                    Q(user=self.request.user) &
                    (Q(reg_mark__startswith=query) |
                     Q(color__startswith=query) |
                     Q(model__startswith=query)) & Q(is_banned=True)
                ).order_by('confirmed')
        else:
            if self.request.user.is_superuser:
                cars = Car.objects.filter(is_banned=True).order_by('confirmed')
            else:
                cars = Car.objects.filter(user=self.request.user)

        cars = cars.prefetch_related('ban_set')
        return cars



@method_decorator(login_required, name='dispatch')
class DebtorListView(ListView):
    model = Profile
    template_name = 'parking/debtor_list.html'
    context_object_name = 'debtors'

    def get_queryset(self):
        return self.model.objects.filter(balance__lt=0)


# class DownloadCSVView(View):
#     model = Payment
#     fields = ['']

#     def get(self, request, *args, **kwargs):
#         debtors = 
#         response = HttpResponse(content_type='text/csv')
#         response['Content-Disposition'] = 'attachment; filename="debtor_report.csv"'

#         if blob_content:
#             response = HttpResponse(blob_content.readall(), content_type=file_type)
#             response['Content-Disposition'] = f'attachment; filename={filename}'
#             messages.success(request, f"{filename} was successfully downloaded")
#             return response

#         return Http404


@login_required
def parking_report(request):
    if request.user.is_superuser:
        cars = Car.objects.all()
    else:
        cars = Car.objects.filter(user=request.user)


@method_decorator(login_required, name='dispatch')
class HistoryView(TemplateView):
    template_name = "parking/history.html"

    def get_context_data(self, **kwargs) -> dict[str]:
        context = super().get_context_data(**kwargs)

        context['history'] = Park.objects.filter(car__user=self.request.user).order_by('-in_time').values(
            'car__reg_mark',
            'in_time',
            'out_time',
            'cost',
            'out_time')
        return context


@method_decorator(login_required, name='dispatch')
class ParkingGreetView(DetailView):
    template_name = "parking/parking_greet.html"
    model = Park

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['duration'] = context['object'].duration_to_str()
        context['payment'] = self.request.user.profile

        return context


@method_decorator(superuser_required, name='dispatch')
class SettingsView(UpdateView):
    model = ParkingInfo
    fields = ['address', 'places', 'limit', 'default_fare']
    success_url = reverse_lazy('parking:parking_info')

    def get_object(self, queryset=None) -> Model:
        first = ParkingInfo.objects.first()
        # We need to be shure that we hawe a record
        if first is None:
            object = ParkingInfo.objects.create()
        else:
            object = ParkingInfo.objects.get(id=first.id)
        return object


@login_required
def parking(request):
    if request.method == 'GET':
        message = ''
        if request.user.profile.balance < 0:
            message = "You cann't park your car due to parking debt! Please, repay the debt."

    if request.method == 'POST':
        car = None
        text = []
        message = f"Your car number was not detected or not register. Please contact the administrator!"
        for file_name in request.FILES:
            file = bytearray(request.FILES[file_name].read())
            text = CarPlateReader().img_process(file)
            car = Car.objects.filter(user=request.user, reg_mark__in=text).first()

            if car is not None:
                break

        if car is not None and \
            car.confirmed and \
            not car.is_banned and \
            request.user.profile.balance >= 0:

            park = Park.objects.filter(car=car, out_time=None).first()

            if park:
                park.out_time = datetime.now(timezone.utc)
                park.save()

            else:
                park = Park(car=car)
                park.save()

            return redirect('parking:parking_greet', park.pk)

        else:
            if text:
                message = f"Your car number {''.join(text)} not register. Plase contact the administrator!"
            else:
                message = f"Your car number was not detected. Plase try again!"
            return render(request, 'parking/parking.html', {'message': message, 'car': car})

    return render(request, 'parking/parking.html', {'message': message})


@login_required
def parking_report(request):
    if request.user.is_superuser:
        cars = Car.objects.all()
    else:
        cars = Car.objects.filter(user=request.user)

    reports = []
    for car in cars:
        total_duration = car.total_parking_duration()
        hours, remainder = divmod(total_duration, 3600)
        minutes, seconds = divmod(remainder, 60)
        total_duration_str = '{:02}:{:02}:{:02}'.format(int(hours), int(minutes), int(seconds))
        total_cost = car.total_parking_cost()
        reports.append({
            'registration_mark': car.reg_mark,
            'total_duration': total_duration_str,
            'total_cost': total_cost,
            'user': car.user
        })

    return render(request, 'parking/report.html', {'reports': reports})


def is_admin(user):
    return user.is_superuser


@user_passes_test(is_admin)
def download_reports(request):
    cars = Car.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="all_parking_reports.csv"'

    writer = csv.writer(response)
    writer.writerow(['Registration Mark', 'Total Duration (seconds)', 'Total Cost', 'User'])

    for car in cars:
        total_duration = car.total_parking_duration()
        total_cost = car.total_parking_cost()
        writer.writerow([car.reg_mark, total_duration, total_cost, car.user.username])

    return response


@csrf_protect
def delete_car(request, id):
    if request.method == 'POST':
        item = get_object_or_404(Car, id=id)
        item.delete()
        return redirect('parking:cars')
    return HttpResponse(status=405)


@csrf_protect
def edit_car(request, id):
    item = get_object_or_404(Car, id=id)
    if request.method == 'POST':
        form = CarForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('parking:cars')
    else:
        form = CarForm(instance=item)

parking_system/parking/templates/parking/ban_list.html
{% extends "parking/base.html" %}

{% block content %}
<div class="row">
    <div class="d-flex justify-content-center">
        <div class="col-12">
            <div class="container text-center">
                <h2 class="display-6 fw-normal text-body-emphasis mb-3">Banned cars</h2>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <form id="search-form" class="form-inline">
                    <input id="search-input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" required>
                </form>
            </div>
            <div id="car-list" class="table-responsive">
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th class="col-1" scope="col">ID</th>
                    <th class="col-1" scope="col">Registration mark</th>
                    <th class="col-2" scope="col">Model</th>
                    <th class="col-2" scope="col">Color</th>
                    <th class="col-2" scope="col">Owner</th>
                    <th class="col-3" scope="col">Reason</th>
                    <th class="col-1" scope="col"></th>
                    </tr>
                </thead>
                <tbody id="car-table-body">
                    {% for car in banned_cars %}
                    <tr>
                    <td>{{ car.id }}</td>
                    <td>{{ car.reg_mark }}</td>
                    <td>{{ car.model }}</td>
                    <td>{{ car.color }}</td>
                    <td>{{ car.user }}</td>
                    <td>
                        {% for ban in car.ban_set.all %}
                            {{ ban.reason }}
                        {% endfor %}
                    </td>
                    <td></td>
                    {% if user.is_superuser %}
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
                                    <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                                    <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
                                </svg>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                <li>
                                    <a href="{% url 'parking:edit_car' id=car.id %}" class="btn btn-outline-orange">Edit</a>
                                </li>
                                <li>
                                    <form method="POST" action="{% url 'parking:delete_car' id=car.id %}" style="display: inline;">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-grey" type="submit">Delete</button>
                                    </form>
                                </li>
                                {% if car.is_banned %}
                                <li>
                                    <form method="POST" action="{% url 'parking:unban_car' car.id %}" style="display: inline;">
                                        {% csrf_token %}
                                        <button class="btn btn-outline-green" type="submit">Unban</button>
                                    </form>
                                </li>
                                {% else %}
                                <li>
                                    <form method="POST" action="{% url 'parking:ban_car' car.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-outline-red">Ban</button>
                                    </form>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </td>
                    {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var searchInput = document.getElementById('search-input');

            searchInput.addEventListener('input', function() {
                var query = this.value.trim();
                if (query.length >= 1 || query.length === 0) {
                    searchCars(query);
                }
            });

            function searchCars(query) {
                var url = "{% url 'parking:search_banned_cars' %}?q=" + encodeURIComponent(query);

                fetch(url)
                    .then(response => response.text())
                    .then(data => {
                        var tempDiv = document.createElement('div');
                        tempDiv.innerHTML = data;

                        var tableBody = tempDiv.querySelector('#car-table-body');
                        document.getElementById('car-table-body').innerHTML = tableBody.innerHTML;
                    })
                    .catch(error => {
                        console.error('Ошибка:', error);
                    });
            }
        });
    </script>
</div>
{% endblock %}

parking_system/parking/templates/parking/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Smart Parking Manager</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        {% load static %}
        <link rel="icon" href="{% static 'parking/favicon.ico' %}" type="image/x-icon">
        <style>
            .action-buttons {
                display: flex;
                gap: 10px;
            }

            .btn-outline-orange {
                color: #fd7e14;
                background-color: #fff;
            }
            .btn-outline-orange:hover {
                color: #fff;
                background-color: #fd7e14;
                border-color: #fd7e14;
            }
            .btn-outline-grey {
                color: #6c757d;
                background-color: #fff;
            }
            .btn-outline-grey:hover {
                color: #fff;
                background-color: #6c757d;
                border-color: #6c757d;
            }
            .btn-outline-green {
                color: #2AF8DF;
                background-color: #fff;
            }
            .btn-outline-green:hover {
                color: #fff;
                background-color: #2AF8DF;
                border-color: #2AF8DF;
            }
            .btn-outline-red {
                color: #F5B7B1;
                background-color: #fff;
            }
            .btn-outline-red:hover {
                color: #fff;
                background-color: #F5B7B1;
                border-color: #F5B7B1;
            }
            .dropdown-menu {
                z-index: 1050;
            }
            .table-responsive {
                overflow: visible;
            }
            .form-check-input {
                border-color: #007bff;
                background-color: #fff;
            }
            .form-check-input:checked {
                background-color: #007bff;
                border-color: #007bff;
            }
            .confirmed-true {
                color: green;
            }
            .confirmed-false {
                color: red;
            }
            .dropdown-toggle::after {
                display: none;
            }
            .dropdown {
                position: relative;
            }
            .dropdown-toggle {
                display: flex;
                align-items: center;
                justify-content: center;
                padding: 0.375rem 0.75rem;
            }
            .search-add-container {
                display: flex;
                justify-content: space-between;
                align-items: center;
                margin-bottom: 1rem;
            }
            .search-add-container .input-group {
                flex: 1;
                max-width: 300px;
                margin-right: 1rem;
            }
            .left-align {
                text-align: left;
            }
            .flex-fill {
                flex: 1;
            }
        </style>
    </head>
    <body>
        <main class="container">
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                <div class="col-md-3 mb-2 mb-md-0">
                    <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                        <img class="bi" width="72" height="57" src="{% static 'parking/logo.jpg' %}" aria-label="Bootstrap"></img>
                        <span class="fs-4 mt-2">Smart Parking Manager</span>
                    </a>
                </div>
                <ul class="nav nav-underline">
                    <li class="nav-item"><a href="{% url 'parking:cars' %}" {% if request.resolver_match.url_name == "cars" %} class="nav-link active" {% else %} class="nav-link" {% endif %} aria-current="page">Cars</a></li>
                    {% if user.is_superuser %}
                    <li class="nav-item"><a href="{% url 'parking:parking_info' %}" {% if request.resolver_match.url_name == "settings" %} class="nav-link active" {% else %} class="nav-link" {% endif %} aria-current="page">Parking info</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown" data-bs-toggle="dropdown" aria-expanded="true" aria-current="page" style="padding: 0.5rem 0.375rem">Reports</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown">
                          <li><a class="dropdown-item" href="{% url 'parking:parking_report' %}" class="" >Parking report</a></li>
                          <li><a class="dropdown-item" href="{% url 'parking:debtor_report' %}">Debtor report</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    <li class="nav-item"><a href="{% url 'parking:history' %}" {% if request.resolver_match.url_name == "history" %} class="nav-link active" {% else %} class="nav-link" {% endif %} aria-current="page">History</a></li>
                    <li class="nav-item"><a href="{% url 'users:profile' %}" {% if request.resolver_match.url_name == "profile" %} class="nav-link active" {% else %} class="nav-link" {% endif %} aria-current="page">Profile</a></li>
                    {% if user.is_superuser %}
                    <li class="nav-item"><a href="{% url 'parking:ban_list' %}" {% if request.resolver_match.url_name == "ban_list" %} class="nav-link active" {% else %} class="nav-link" {% endif %}>Ban List</a></li>
                    {% else %}
                    <li class="nav-item"><a href="{% url 'parking:payment' %}" {% if request.resolver_match.url_name == "ban_list" %} class="nav-link active" {% else %} class="nav-link" {% endif %}>Payments {% if user.profile.balance < 0 %}<span class="badge rounded-pill text-bg-danger">!</span>{% endif %}</a></li>
                    {% endif %}
                </ul>
                <div class="col-md-3 text-end">
                    {% if user.username %}
                    <form method="POST" action="{% url 'users:signout' %}">
                        {% csrf_token %}
                        <span>Hi, <b>{{ user.username }}! </b></span>
                        <a href="{% url 'parking:parking' %}" class="btn btn-primary" role="button">Parking</a>
                        <button type="submit" class="btn btn-outline-primary me-2">Sign-out</button>
                    </form>
                    {% else %}
                    <form method="POST" action="{% url 'users:signin' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary me-2">Sign-in</button>
                    </form>
                    {% endif %}
                </div>
              </header>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

parking_system/parking/templates/parking/pay.html
{% extends "parking/base.html" %}

{% block content %}
<div class="d-flex justify-content-center">
    <div id="liqpay_checkout"></div>
    <script>
        window.LiqPayCheckoutCallback = function() {
            LiqPayCheckout.init({
                data: "{{ data }}",
                signature: "{{ signature }}",
                embedTo: "#liqpay_checkout",
                mode: "embed" // embed || popup,
            }).on("liqpay.callback", function(data){
                setTimeout(function() {
                window.location.href = "{% url 'parking:payment' %}"; // Replace with your target URL
            }, 5000); // 5000 milliseconds = 5 seconds
            }).on("liqpay.ready", function(data){
                // ready
            }).on("liqpay.close", function(data){
                // close
            });
        };
    </script>
    <script src="//static.liqpay.ua/libjs/checkout.js" async></script>
</div>
{% endblock %}